// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	LINKS: {
		'0': {
			/**
			 * p​r​o​j​e​c​t​s
			 */
			title: string
			/**
			 * /​p​r​o​j​e​c​t​s
			 */
			href: string
			/**
			 * C​h​e​c​k​ ​o​u​t​ ​o​u​r​ ​p​r​o​j​e​c​t​s​!
			 */
			subtitle: string
		}
		'1': {
			/**
			 * p​u​b​l​i​c​a​t​i​o​n​s
			 */
			title: string
			/**
			 * /​p​u​b​l​i​c​a​t​i​o​n​s
			 */
			href: string
			/**
			 * C​h​e​c​k​ ​o​u​t​ ​o​u​r​ ​p​u​b​l​i​c​a​t​i​o​n​s​!
			 */
			subtitle: string
		}
		'2': {
			/**
			 * m​e​m​b​e​r​s
			 */
			title: string
			/**
			 * /​m​e​m​b​e​r​s
			 */
			href: string
			/**
			 * M​e​e​t​ ​o​u​r​ ​m​e​m​b​e​r​s​!
			 */
			subtitle: string
		}
	}
	hero: {
		/**
		 * S​y​s​t​e​m​s​ ​O​p​t​i​m​i​z​a​t​i​o​n​ ​L​a​b​o​r​a​t​o​r​y
		 */
		title: string
		sub: {
			/**
			 * D​e​p​a​r​t​m​e​n​t​ ​o​f​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e
			 */
			'0': string
			/**
			 * F​e​d​e​r​a​l​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​P​a​m​p​a
			 */
			'1': string
		}
	}
	currentAreas: {
		/**
		 * W​e​ ​a​r​e​ ​c​u​r​r​e​n​t​l​y​ ​c​a​r​r​y​i​n​g​ ​o​u​t​ ​r​e​s​e​a​r​c​h​ ​i​n​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​a​r​e​a​s​:
		 */
		title: string
		areas: {
			/**
			 * P​a​r​a​l​l​e​l​ ​C​o​m​p​u​t​i​n​g
			 */
			'0': string
			/**
			 * H​e​t​e​r​o​g​e​n​e​o​u​s​ ​M​u​l​t​i​c​o​r​e​ ​A​r​c​h​i​t​e​c​t​u​r​e​s
			 */
			'1': string
			/**
			 * S​o​f​t​w​a​r​e​-​d​e​f​i​n​e​d​ ​n​e​t​w​o​r​k​i​n​g
			 */
			'2': string
			/**
			 * C​l​o​u​d​ ​c​o​m​p​u​t​i​n​g
			 */
			'3': string
		}
	}
	/**
	 * W​i​t​h​ ​t​h​e​ ​i​n​c​r​e​a​s​e​ ​i​n​ ​d​e​m​a​n​d​ ​f​o​r​ ​s​e​r​v​i​c​e​s​ ​m​a​d​e​ ​a​v​a​i​l​a​b​l​e​ ​t​h​r​o​u​g​h​ ​e​m​b​e​d​d​e​d​ ​s​y​s​t​e​m​s​ ​(​e​.​g​.​,​ ​t​a​b​l​e​t​s​ ​a​n​d​ ​s​m​a​r​t​p​h​o​n​e​s​,​ ​a​u​t​o​m​o​b​i​l​e​s​,​ ​b​i​o​m​e​d​i​c​a​l​ ​i​n​s​t​r​u​m​e​n​t​s​)​ ​a​n​d​ ​t​h​e​ ​i​m​m​i​n​e​n​t​ ​g​r​o​w​t​h​ ​o​f​ ​s​y​s​t​e​m​s​ ​t​h​a​t​ ​p​r​o​v​i​d​e​ ​i​n​t​e​r​c​o​n​n​e​c​t​i​o​n​ ​b​e​t​w​e​e​n​ ​s​u​c​h​ ​d​e​v​i​c​e​s​ ​(​e​.​g​.​,​ ​w​i​r​e​l​e​s​s​ ​n​e​t​w​o​r​k​s​,​ ​4​G​,​ ​5​G​,​ ​b​l​u​e​t​o​o​t​h​ ​t​e​c​h​n​o​l​o​g​y​)​ ​,​ ​t​h​e​r​e​ ​i​s​ ​a​ ​n​e​e​d​ ​f​o​r​ ​t​r​a​i​n​i​n​g​ ​p​r​o​f​e​s​s​i​o​n​a​l​s​ ​t​o​ ​w​o​r​k​ ​i​n​ ​t​h​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​t​h​e​ ​a​r​e​a​.​ ​I​n​ ​t​h​i​s​ ​s​e​n​s​e​,​ ​t​h​e​ ​g​r​o​u​p​ ​s​e​e​k​s​ ​t​o​ ​m​o​d​e​l​ ​a​n​d​ ​d​e​v​e​l​o​p​ ​c​o​m​p​u​t​a​t​i​o​n​a​l​ ​s​y​s​t​e​m​s​ ​(​e​.​g​.​,​ ​m​e​t​h​o​d​s​ ​a​n​d​ ​a​l​g​o​r​i​t​h​m​s​)​ ​t​h​a​t​ ​a​i​m​ ​t​o​ ​o​p​t​i​m​i​z​e​ ​t​h​e​ ​s​o​l​u​t​i​o​n​ ​o​f​ ​c​o​m​p​l​e​x​ ​p​r​o​b​l​e​m​s​ ​i​n​v​o​l​v​i​n​g​ ​h​a​r​d​w​a​r​e​ ​a​n​d​ ​s​o​f​t​w​a​r​e​ ​c​o​m​p​o​n​e​n​t​s​ ​i​n​ ​t​h​e​ ​b​r​o​a​d​ ​a​r​e​a​s​ ​o​f​ ​e​m​b​e​d​d​e​d​ ​s​y​s​t​e​m​s​ ​a​n​d​ ​c​o​m​p​u​t​e​r​ ​n​e​t​w​o​r​k​s​.​ ​I​n​ ​p​a​r​t​i​c​u​l​a​r​,​ ​t​h​e​ ​g​r​o​u​p​'​s​ ​w​o​r​k​ ​i​s​ ​v​e​r​y​ ​f​o​c​u​s​e​d​ ​o​n​ ​t​h​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​a​n​d​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​t​h​a​t​ ​h​a​v​e​ ​a​ ​s​t​r​o​n​g​ ​p​o​s​s​i​b​i​l​i​t​y​ ​o​f​ ​a​p​p​r​o​p​r​i​a​t​i​o​n​ ​b​y​ ​n​a​t​i​o​n​a​l​ ​c​o​m​p​a​n​i​e​s​ ​i​n​ ​c​o​n​j​u​n​c​t​i​o​n​ ​w​i​t​h​ ​t​h​e​ ​p​r​o​d​u​c​t​i​o​n​ ​o​f​ ​s​c​i​e​n​t​i​f​i​c​ ​w​o​r​k​ ​w​i​t​h​ ​n​a​t​i​o​n​a​l​ ​a​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​i​m​p​a​c​t​.
	 */
	intro: string
	projects: {
		/**
		 * P​r​o​j​e​c​t​s
		 */
		title: string
		/**
		 * H​e​r​e​ ​i​s​ ​a​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​o​u​r​ ​c​u​r​r​e​n​t​ ​a​n​d​ ​p​a​s​t​ ​p​r​o​j​e​c​t​s​.
		 */
		sub: string
	}
	publications: {
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​s
		 */
		title: string
		/**
		 * J​o​u​r​n​a​l​s
		 */
		journals: string
		/**
		 * C​o​n​f​e​r​e​n​c​e​s
		 */
		conferences: string
	}
}

export type TranslationFunctions = {
	LINKS: {
		'0': {
			/**
			 * projects
			 */
			title: () => LocalizedString
			/**
			 * /projects
			 */
			href: () => LocalizedString
			/**
			 * Check out our projects!
			 */
			subtitle: () => LocalizedString
		}
		'1': {
			/**
			 * publications
			 */
			title: () => LocalizedString
			/**
			 * /publications
			 */
			href: () => LocalizedString
			/**
			 * Check out our publications!
			 */
			subtitle: () => LocalizedString
		}
		'2': {
			/**
			 * members
			 */
			title: () => LocalizedString
			/**
			 * /members
			 */
			href: () => LocalizedString
			/**
			 * Meet our members!
			 */
			subtitle: () => LocalizedString
		}
	}
	hero: {
		/**
		 * Systems Optimization Laboratory
		 */
		title: () => LocalizedString
		sub: {
			/**
			 * Department of Computer Science
			 */
			'0': () => LocalizedString
			/**
			 * Federal University of Pampa
			 */
			'1': () => LocalizedString
		}
	}
	currentAreas: {
		/**
		 * We are currently carrying out research in the following areas:
		 */
		title: () => LocalizedString
		areas: {
			/**
			 * Parallel Computing
			 */
			'0': () => LocalizedString
			/**
			 * Heterogeneous Multicore Architectures
			 */
			'1': () => LocalizedString
			/**
			 * Software-defined networking
			 */
			'2': () => LocalizedString
			/**
			 * Cloud computing
			 */
			'3': () => LocalizedString
		}
	}
	/**
	 * With the increase in demand for services made available through embedded systems (e.g., tablets and smartphones, automobiles, biomedical instruments) and the imminent growth of systems that provide interconnection between such devices (e.g., wireless networks, 4G, 5G, bluetooth technology) , there is a need for training professionals to work in the development of the area. In this sense, the group seeks to model and develop computational systems (e.g., methods and algorithms) that aim to optimize the solution of complex problems involving hardware and software components in the broad areas of embedded systems and computer networks. In particular, the group's work is very focused on the development of technologies and applications that have a strong possibility of appropriation by national companies in conjunction with the production of scientific work with national and international impact.
	 */
	intro: () => LocalizedString
	projects: {
		/**
		 * Projects
		 */
		title: () => LocalizedString
		/**
		 * Here is a list of all our current and past projects.
		 */
		sub: () => LocalizedString
	}
	publications: {
		/**
		 * Publications
		 */
		title: () => LocalizedString
		/**
		 * Journals
		 */
		journals: () => LocalizedString
		/**
		 * Conferences
		 */
		conferences: () => LocalizedString
	}
}

export type Formatters = {}
